# Generated by Django 4.1.2 on 2023-03-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_student_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.CharField(choices=[(2, 1), (3, 2), (4, 3), (5, 4)], default=4, max_length=2),
        ),
    ]
