# Generated by Django 4.1.2 on 2023-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_student_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mark',
            field=models.CharField(choices=[('1', '2'), ('2', '3'), ('3', '4'), ('4', '5')], default=4, max_length=9),
        ),
    ]
